### ISSUE TITLE
State of gravity-prisma?

### ISSUE THREAD

**Issue by omar-dulaimi** [digital-loukoum/gravity#10]
Hello

I noticed that the documentation of `gravity-prisma` is in a folder called `removed` and the link to setup Prisma is down. 
So, is it deprecated and should not be used?

**Comment by Gin-Quin** [comment]
It is not deprecated but waiting for a rework. As soon as I finished to rework the Prisma integration it will be available again.

Right now you can still use Prisma along Gravity, you will only miss some cool features like creating a Gravity service directly from a Prisma model. The problem is that the input types of some Prisma functions (like `create`) get absolutely huge when your model has a relation which demultiply the size of `schema.json`.

I intend to create a proxy to Prisma models with simpler types and use this proxy instead to make a Gravity service.

**Comment by omar-dulaimi** [comment]
Sounds great. Thanks for letting me know.
Excited to try it out when it becomes available.

Thank you for your work.
